# Generated by Django 5.1.5 on 2025-02-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
