# Generated by Django 5.1.5 on 2025-02-25 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_order_ordered_date_cart_ordered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='ordered_date',
        ),
    ]
