# Generated by Django 5.1.5 on 2025-03-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_order_ordered_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user_comment',
        ),
    ]
