# Generated by Django 5.1.5 on 2025-02-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_shippingaddress_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_2',
            field=models.CharField(blank=True, help_text='Bâtiment, étage, appartement, etc.', max_length=1024, null=True),
        ),
    ]
