# Generated by Django 5.1.5 on 2025-03-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_shippingaddress_address_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopper',
            name='last_transaction_trace_id',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
